from pyspark.sql.functions import sum, count, avg


def calculate_customer_revenue(df):
    """
    Calculate total revenue generated by each customer.
    """

    return (
        df.groupBy("customer_id")
        .agg(
            sum("total_amount").alias("total_revenue")
        )
        .orderBy(
            "total_revenue",
            ascending=False
        )
    )


def calculate_customer_metrics(df):
    """
    Calculate customer-level business metrics.
    """

    return (
        df.groupBy("customer_id")
        .agg(
            sum("total_amount").alias("total_revenue"),
            count("*").alias("number_of_orders"),
            avg("total_amount").alias("average_order_value")
        )
        .orderBy(
            "total_revenue",
            ascending=False
        )
    )